### ISSUE TITLE
Book builds are making "figure" HTML flags instead of "div", leading to uncentered images.

### ISSUE THREAD

**Issue by mathieuboudreau** [neurolibre/neurolibre#15]
Related to #13

See this comparison (left is the HTML from the book build on RoboNeuro, right is my local book build):
<img width="985" alt="Screen Shot 2021-09-17 at 12 44 12 AM" src="https://user-images.githubusercontent.com/1421029/133721119-a4cdbee9-b3fc-462c-83e3-10391e8508f7.png">

This leads to my PNG figures being left aligned (neurolibre),

<img width="1440" alt="Screen Shot 2021-09-16 at 11 46 23 AM" src="https://user-images.githubusercontent.com/1421029/133721223-8bb81867-7d2d-47d5-bb77-ef4cb4ecfec5.png">

instead of centered (local),

<img width="1440" alt="Screen Shot 2021-09-16 at 11 55 43 AM" src="https://user-images.githubusercontent.com/1421029/133721255-69f78e80-7706-45f9-a5fe-f15202110332.png">

as I set it up in my markdown file,

<img width="506" alt="Screen Shot 2021-09-17 at 12 51 32 AM" src="https://user-images.githubusercontent.com/1421029/133721387-68dae125-ccf6-4502-a038-25b6cfce0c2a.png">

**Comment by ltetrel** [comment]
This is maybe something you could ask to the jupyter team itself ? Personally I have no idea what would cause that,

**Comment by mathieuboudreau** [comment]
Solved in https://github.com/qMRLab/t1_book/commit/7b98a2d3cc8f5e130c8d9f0570202a0a96740e88

No idea why the centering would work on local builds and not Binder builds (the pip environments were almost identical; I tried matching as close as possible on the different os-es), however this change resolved it:

<img width="1227" alt="Screen Shot 2021-09-17 at 2 00 09 PM" src="https://user-images.githubusercontent.com/1421029/133826883-cdd672ee-f795-484a-bc28-2654be938aaa.png">

**Comment by ltetrel** [comment]
This seem to be an issue with the docker environment itself (and jupyter book), not necessarily the Neurolibre backend.
Happy to see you resolved it!
