### ISSUE TITLE
Roboneuro status badge is off

### ISSUE THREAD

**Issue by pbellec** [neurolibre/neurolibre#20]
There is not enough space for "neurolibre"

[![status](http://neurolibre.herokuapp.com/papers/eceea8a92584feae6cb1ac67d5eb2a01/status.svg)](http://neurolibre.herokuapp.com/papers/eceea8a92584feae6cb1ac67d5eb2a01)

**Comment by emdupre** [comment]
(transferred to `neurolibre`, since the issue templates are included in this codebase rather than in `roboneuro` 's )

**Comment by agahkarakuzu** [comment]
Spacing problem with roboneuro/neurolibre status badges has been fixed at https://github.com/neurolibre/neurolibre/pull/35/commits/66913b5a2bbac0a64fd9ec0747edbaadcd031a87.

Example: https://neurolibre.herokuapp.com/papers/10.55458/neurolibre.00007
