### ISSUE TITLE
Typo in message after initial sign-in

### ISSUE THREAD

**Issue by tsalo** [neurolibre/neurolibre#21]
After signing in with my ORCID for the first time, the following message appeared (emphasis mine):

> Before you can submit a **notebok** to NeuroLibre, you need to add your email address and GitHub handle to your profile →.

The typo seems to be located at:

https://github.com/neurolibre/neurolibre/blob/2a9c8e81d4e9d5ad1cab3902dac25fc212179b87/app/views/shared/_profile.html.erb#L2

**Comment by pbellec** [comment]
Thanks for reporting!
