### ISSUE TITLE
modify xml for preprints

### ISSUE THREAD

**Issue by pbellec** [neurolibre/neurolibre#27]
There are differences between regular xml publication records and an xml preprint record. Note from crossref:

For your preprints to be deposited with the correct type, you'll need to register them using the posted content metadata schema (see[ examples in the posted content markup guide](https://www.crossref.org/education/content-registration/content-type-markup-guide/posted-content-includes-preprints/)). This helps ensure the preprints you post are correctly represented in other systems that use Crossref metadata. You can only register preprints by sending us an XML file - you can't currently register preprints using one of our helper tools.

**Comment by agahkarakuzu** [comment]
https://github.com/neurolibre/roboneuro/pull/28
