### ISSUE TITLE
doi meta-data in repo2data

### ISSUE THREAD

**Issue by pbellec** [neurolibre/neurolibre#29]
I am proposing that we add a doi field in repo2data configuration. 
This doi will need to be verified by reviewers, but should resolve to a stable archive of the data.
The doi would then be used in the paper descriptor, for people to reproduce the paper. 

Another possible feature would be to automatically create an archive and DOI on zenodo, for the dataset lacking a DOI at submission. 

This mechanism would allow us to guarantee reproducibility of submissions from archives with DOIs, without duplicating dataset deposition when we don't need it.

**Comment by ltetrel** [comment]
doi minting: Canadian Association of Research Libraries | Association des bibliothèques de recherche du Canada

**Comment by agahkarakuzu** [comment]
Implemented in roboneuro. https://github.com/neurolibre/roboneuro/pull/28
