### ISSUE TITLE
release the neurolibre logo

### ISSUE THREAD

**Issue by pbellec** [neurolibre/neurolibre#30]
we should probably release it formally on zenodo. Thoughts?

**Comment by agahkarakuzu** [comment]
Sure, we can release the brand repo with all the content. I paid some premium licenses, I can upload them there for completeness.

**Comment by agahkarakuzu** [comment]
@pbellec can you archive [this release](https://github.com/neurolibre/brand/releases/tag/v1.0) on Zenodo? I tried but could not pass 2FA to link roboneuro's GH account to Zenodo. I cannot see neurolibre org on my personal Zenodo account neither.

**Comment by agahkarakuzu** [comment]
https://zenodo.org/record/6836262
